### ISSUE TITLE
Error in NetworkExplorer

### ISSUE THREAD

**Issue by marromcb** [biolab/orange3-network#105]
##### Actual behavior 

![errorr-orange](https://user-images.githubusercontent.com/26971441/53052718-b8963c80-345c-11e9-9611-55ba1f22fa1a.jpg)

##### Additional info (worksheets, data, screenshots, ...)
I'm a newbie in Orange3

**Comment by markotoplak** [comment]
The new version of network explorer is not compatible with your version of Orange. Please upgrade Orange to a newer version.

We need to update our package requirements for this not to happen anymore.

**Comment by janezd** [comment]
@marromcb, did you restart Orange after installing the add-on? Can you (re)start it now and see whether the Network widget now works? And, after you do so, can you check which version of Orange you have?

@markotoplak, so Orange is supposed to upgrade when an add-on requires a higher version? I hoped so, but I was not sure. (Does it work?! Seems dangerous if this also requires a newer PyQt... This will surely be safer after canvas is separated from Orange.)

**Comment by markotoplak** [comment]
@janezd, I have no idea what would happen. I never tried, but I do see opportunities for putting your python environment in an inconsistent state if mixing conda and pip on the same system (not all add-ons are conda installable).

But according to requirements, new network add-on and old Orange should not be able to coexist.

**Comment by marromcb** [comment]
First I'll respond ..
@markotoplak I had the new version, but I couldn't download _Networks_ ,someone told me that it works with orange version 3.17, and so it did .. but after that, Network Explorer showed the problem I present...
@janezd yes, also I did that ...

I don't know if it was necessary to mention that I'm using Orange3 under AnacondaNavigator ...
Having said that, **the problem is solved now**, I had to unistall Anaconda, and install it again, I had a last year version to not say and older one, so I installed it again or update it (I think it's the same, isn't it?) , and then update Orange3 to v3.19 and everything worked fine now ..

Thank you so much for your responses !
M

**Comment by marromcb** [comment]
I would like you to correct me if I'm wrong,
@janezd @markotoplak 

I understand that Anaconda has its own version, then Orange3 its own version AND each widget its own version, SO that everything works fine, all of them must to have a version that everything work fine together, I'm imagining three gears that have to have these characteristics to mesh well.... or I'm totally lost?
Thank you in advance
M

**Comment by janezd** [comment]
I don't know about anaconda (I assume it always pulls the latest version?). For Orange and widgets, yes, there may be incompatibilities between versions, but this is rare. Most changes we make are backward compatible. The problem you encountered was related to a big overhaul of all visualization widgets.

However, if everything is configured correctly (as it was in this case!), update mechanism should synchronise versions automatically. We plan some further changes to this add-on, and we'll keep our eyes on what happens at the update.

**Comment by ajdapretnar** [comment]
Just to keep in mind: we need some testing on Anaconda Navigator, because many people seem to use it and we are not even sure which version is installed when. I nominate this for the Friday sprint.
