### ISSUE TITLE
error encounted in NetworkExplorer, Exception: AttributeError: 'GraphView' object has no attribute 'step_resizing'

### ISSUE THREAD

**Issue by joyzhou28** [biolab/orange3-network#119]
##### Network version

orange-Network_1.4.3

##### Orange version

Orange3.19.0

##### Actual behavior
![1](https://user-images.githubusercontent.com/23353880/56561226-43202700-65d9-11e9-8ad2-632ac64044aa.PNG)

##### Additional info (worksheets, data, screenshots, ...)
Exception:
AttributeError: 'GraphView' object has no attribute 'step_resizing'
Module:
orangecontrib.network.widgets.graphview:129
Widget Name:
Network Explorer
Widget Module:
orangecontrib.network.widgets.OWNxExplorer:78
Widget Scheme:
C:\Users\tlcb\AppData\Local\Temp\ows-0mflg6zt.ows.xml
Version:
3.19.0
Environment:
Python 3.7.1 on Windows 7 6.1.7601 AMD64
Installed Packages:
AnyQt==0.0.10, Babel==2.6.0, Bottleneck==1.2.1, Click==7.0, Cython==0.29.2, Flask-Cors==3.0.7, Flask==1.0.2, Jinja2==2.10, Keras-Applications==1.0.7, Keras-Preprocessing==1.0.9, Markdown==3.0.1, MarkupSafe==1.1.0, Orange3-Network==1.4.2, Orange3==3.19.0, Pillow==5.3.0, PyOpenGL==3.1.1a1, PySocks==1.6.8, PyWavelets==1.0.1, PyYAML==3.13, Pygments==2.3.1, QtAwesome==0.5.3, QtPy==1.5.2, SQLAlchemy==1.2.15, Send2Trash==1.5.0, Sphinx==1.8.2, Werkzeug==0.14.1, XlsxWriter==1.1.2, absl-py==0.7.0, alabaster==0.7.12, anaconda-client==1.7.2, anaconda-navigator==1.9.6, anaconda-project==0.8.2, asn1crypto==0.24.0, astor==0.7.1, astroid==2.1.0, astropy==3.1, atomicwrites==1.2.1, attrs==18.2.0, backcall==0.1.0, backports.os==0.1.1, backports.shutil-get-terminal-size==1.0.0, beautifulsoup4==4.6.3, bitarray==0.8.3, bkcharts==0.2, blaze==0.11.3, bleach==3.0.2, bokeh==1.0.2, boto==2.49.0, certifi==2018.11.29, cffi==1.11.5, chardet==3.0.4, cloudpickle==0.6.1, clyent==1.2.2, colorama==0.4.1, comtypes==1.1.7, conda-build==3.17.6, conda-verify==3.1.1, conda==4.6.8, contextlib2==0.5.5, cryptography==2.4.2, cycler==0.10.0, cytoolz==0.9.0.1, dask==1.0.0, datashape==0.5.4, decorator==4.3.0, defusedxml==0.5.0, dill==0.2.8.2, distributed==1.25.1, docutils==0.14, entrypoints==0.2.3, et-xmlfile==1.0.1, fast-histogram==0.5, fastTSNE==0.2.13, fastcache==1.0.2, filelock==3.0.10, future==0.17.1, gast==0.2.2, gevent==1.3.7, glob2==0.6, glue-core==0.14.1, glue-vispy-viewers==0.11, greenlet==0.4.15, grpcio==1.16.1, h5py==2.8.0, heapdict==1.0.0, html5lib==1.0.1, idna==2.8, imageio==2.4.1, imagesize==1.1.0, importlib-metadata==0.6, ipykernel==5.1.0, ipython-genutils==0.2.0, ipython==7.2.0, ipywidgets==7.4.2, isort==4.3.4, itsdangerous==1.1.0, jdcal==1.4, jedi==0.13.2, joblib==0.13.1, jsonschema==2.6.0, jupyter-client==5.2.4, jupyter-console==6.0.0, jupyter-core==4.4.0, jupyter==1.0.0, jupyterlab-server==0.2.0, jupyterlab==0.35.3, keyring==17.0.0, keyrings.alt==3.1.1, kiwisolver==1.0.1, lazy-object-proxy==1.3.1, libarchive-c==2.8, llvmlite==0.26.0, locket==0.2.0, lxml==4.2.5, matplotlib==3.0.2, mccabe==0.6.1, menuinst==1.4.14, mistune==0.8.4, mkl-fft==1.0.6, mkl-random==1.0.2, mock==2.0.0, more-itertools==4.3.0, mpl-scatter-density==0.4, mpmath==1.1.0, msgpack==0.5.6, multipledispatch==0.6.0, navigator-updater==0.2.1, nbconvert==5.4.0, nbformat==4.4.0, networkx==2.2, nltk==3.4, nose==1.3.7, notebook==5.7.4, numba==0.41.0, numexpr==2.6.8, numpy==1.15.4, numpydoc==0.8.0, odo==0.5.1, olefile==0.46, openpyxl==2.5.12, opentsne==0.3.2, packaging==18.0, pandas==0.23.4, pandocfilters==1.4.2, parso==0.3.1, partd==0.3.9, path.py==11.5.0, pathlib2==2.3.3, patsy==0.5.1, pbr==5.1.3, pep8==1.7.1, pickleshare==0.7.5, pip==18.1, pkginfo==1.4.2, plotly==3.5.0, pluggy==0.8.0, ply==3.11, prometheus-client==0.5.0, prompt-toolkit==2.0.7, protobuf==3.6.1, psutil==5.4.8, py==1.7.0, pyOpenSSL==18.0.0, pycodestyle==2.4.0, pycosat==0.6.3, pycparser==2.19, pycrypto==2.6.1, pycurl==7.43.0.2, pyflakes==2.0.0, pylint==2.2.2, pyodbc==4.0.25, pyparsing==2.3.0, pyqtgraph==0.10.0, pyreadline==2.1, pytest-arraydiff==0.3, pytest-astropy==0.5.0, pytest-doctestplus==0.2.0, pytest-openfiles==0.3.1, pytest-remotedata==0.3.1, pytest==4.0.2, python-dateutil==2.7.5, python-louvain==0.11, pytz==2018.7, pywin32==223, pywinpty==0.5.5, pyzmq==17.1.2, qtconsole==4.4.3, requests==2.21.0, retrying==1.3.3, rope==0.11.0, ruamel-yaml==0.15.46, scikit-image==0.14.1, scikit-learn==0.20.1, scipy==1.1.0, seaborn==0.9.0, serverfiles==0.3.0, setuptools==40.6.3, simplegeneric==0.8.1, singledispatch==3.4.0.3, six==1.12.0, snowballstemmer==1.2.1, sortedcollections==1.0.1, sortedcontainers==2.1.0, sphinxcontrib-websupport==1.1.0, spyder-kernels==0.3.0, spyder==3.3.2, statsmodels==0.9.0, sympy==1.3, tables==3.4.4, tblib==1.3.2, tensorboard==1.13.1, tensorflow-estimator==1.13.0, tensorflow==1.13.1, termcolor==1.1.0, terminado==0.8.1, testpath==0.4.2, toolz==0.9.0, tornado==5.1.1, tqdm==4.28.1, traitlets==4.3.2, unicodecsv==0.14.1, urllib3==1.24.1, wcwidth==0.1.7, webencodings==0.5.1, wheel==0.32.3, widgetsnbextension==3.4.2, win-inet-pton==1.0.1, win-unicode-console==0.5, wincertstore==0.2, wrapt==1.10.11, xlrd==1.2.0, xlwings==0.15.1, xlwt==1.3.0, zict==0.1.3
Machine ID:
24062491136
Stack Trace:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 579, in create_widget_instance
    widget.__init__()
  File "D:\Anaconda3\pkgs\orange3-network\orangecontrib\network\widgets\OWNxExplorer.py", line 78, in __init__
    super().__init__()
  File "D:\Anaconda3\lib\site-packages\Orange\widgets\visualize\utils\widget.py", line 378, in __init__
    self.setup_gui()
  File "D:\Anaconda3\lib\site-packages\Orange\widgets\visualize\utils\widget.py", line 382, in setup_gui
    self._add_graph()
  File "D:\Anaconda3\lib\site-packages\Orange\widgets\visualize\utils\widget.py", line 387, in _add_graph
    self.graph = self.GRAPH_CLASS(self, box)
  File "D:\Anaconda3\pkgs\orange3-network\orangecontrib\network\widgets\graphview.py", line 129, in __init__
    self.step_resizing.connect(self.update_edges)
AttributeError: 'GraphView' object has no attribute 'step_resizing'

Local Variables:
OrderedDict([('__class__',
              <class 'orangecontrib.network.widgets.graphview.GraphView'>),
             ('master',
              <orangecontrib.network.widgets.OWNxExplorer.OWNxExplorer object at 0x000000001B65D3A8>),
             ('parent',
              <PyQt5.QtWidgets.QGroupBox object at 0x000000000AF74558>),
             ('self',
              <orangecontrib.network.widgets.graphview.GraphView object at 0x000000000C90E588>)])

**Comment by janezd** [comment]
You are using Orange 3.19, while the current version is 3.21.

However, I suppose you got this version of the add-on directly from github? It has not been released yet because it depends on features from (soon to be released) Orange 3.22.

If you want to use the add-on in this form, update Orange to the current development version from Github. Alternatively, downgrade the add-on to the last released version.

I recommend the latter. Development version of this add-on is currently highly unstable.
