### ISSUE TITLE
Network File: prettify the I/O status bar

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#125]
Status bar reports the same thing twice. Avoid this for clarity.
I'd go with `1239 nodes, 3963 edges, undirected network`.

<img width="451" alt="Screen Shot 2019-08-21 at 10 25 42" src="https://user-images.githubusercontent.com/12524972/63432106-bcf9dd00-c420-11e9-9cfe-ac6bda05a2b9.png">

**Comment by janezd** [comment]
Can't.  The first line comes is the same as in the status bar. I can do

```
1239 nodes, 3963 edges
Undirected network.
```

Would this be OK?

**Comment by ajdapretnar** [comment]
Yes, suer. It was just a suggestion. I thought having it said twice makes really no sense. :)

**Comment by matejklemen** [comment]
Unless I'm missing something obvious, the status bar also displays inconsistent information. In the first line, it reports 1239 nodes and 3963 edges, while in the next line, it reports the numbers switched around :smile:
