### ISSUE TITLE
Error while trying to replicate clustering example

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3-network#140]
Error while trying to replicate https://orange3-network.readthedocs.io/en/latest/widgets/networkclustering.html
![Screenshot from 2019-09-18 17-16-24](https://user-images.githubusercontent.com/47607471/65161652-3db7f300-da38-11e9-861c-5e4c372d1f99.png)

##### Orange version
3.24, Network 1.4.2

**Comment by janezd** [comment]
Fixed in #137. I hope to make a new release of add-on Friday or even tomorrow.

**Comment by Hrovatin** [comment]
SOLVED-can be ignored
I have tried to perform clustering again - it works with some networks, but not all of them. Namely, if node description tsv file is not present in same directory the clustering fails (although I never load the tsv file in Orange in either case). 
The structure of workflow is:Network File->Network Clustering->Network Explorer
