### ISSUE TITLE
Suggestion: automatically show subset on Network Explorer 

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3-network#144]
When importing data and subset data into Network Explorer it is required to select an option to label subset before subset is labeled on graph. Could Network Explorer be changed to automatically select this option when the subset is first feed in the Network Explorer and when a new subset is chosen.

**Comment by ajdapretnar** [comment]
I can't even get the subset to show in the plot. 🤷‍♀ 

1. Connecting a selection should automatically be used as a subset, just like in Scatter Plot.
2. Subset should be highlighted like in Scatter Plot.
3. Labels can be turned on, but only when a Label is set.
