### ISSUE TITLE
Network Explorer: no subset shown

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#158]
##### Network version

1.5.1-dev

##### Orange version

3.24.dev

##### Expected behavior
Network Explorer highlights a subset just like Scatter Plot.

##### Actual behavior
Network Explorer shows no subset.
Also, when a subset is selected and sent to Network Explorer, I have to manually set it to Node Subset every time. A better (smarter) default would be nice, if possible.

##### Steps to reproduce the behavior
Network File (leu_by_genesets.net) - Network Explorer - select a subset in a Data Table or another Network Explorer - use it as a subset in the first Network Explorer.

##### Additional info (worksheets, data, screenshots, ...)
<img width="1008" alt="Screen Shot 2019-11-26 at 11 48 57" src="https://user-images.githubusercontent.com/12524972/69623227-c2c81580-1042-11ea-81d7-152e42079b78.png">

**Comment by Hrovatin** [comment]
For me it works if I select an option to show subset in "(Select criteria for marking)" box at the bottom.

**Comment by Hrovatin** [comment]
To show subset this must be selected in box at the bottom ("(Select criteria for marking.)").

**Comment by ajdapretnar** [comment]
I don't think this is how it should work. I am expecting the subset to be highlighted as in other scatterplot-based widgets. Also marking is not the same as highlighting a subset. The second signal should default to subset, if possible. What do you think, @janezd?

**Comment by Hrovatin** [comment]
Yes, I had quite some trouble making it work.
