### ISSUE TITLE
Bug in orangecontrib.network.network.base.py

### ISSUE THREAD

**Issue by icejean** [biolab/orange3-network#162]
##### Network version

1.5.0

##### Orange version

3.24.1

##### Expected behavior
Network explorer should work when filtering nodes with connections of directed graph.

##### Actual behavior
Network explorer promts error when filtering nodes with connections of directed graph.

##### Steps to reproduce the behavior
Read in a directed graph, and try to filter nodes with connections in network explorer.

##### Additional info (worksheets, data, screenshots, ...)
bug in orangecontrib.network.network.base.py, in the degrees() function of the DirectedEdges() class

def degrees(self, *, weighted=False):
    return self._compute_degrees(self.edges, weighted) \
           + self._compute_degrees(self.in_edges, weighted)
           # the original line is wrong
           # + self.compute_degrees(self.in_edges, weighted)

**Comment by ajdapretnar** [comment]
I can't reproduce this. Please be more precise when describing the steps to reproduce.

Can you check @janezd?

**Comment by janezd** [comment]
Yes, that's obviously wrong. Thanks for reporting! And sorry for not taking care of it sooner.

This add-on would need unittests. And more love. :(
