### ISSUE TITLE
Connect orange3-network to igraph-python with spyder

### ISSUE THREAD

**Issue by icejean** [biolab/orange3-network#163]
##### Additional info (worksheets, data, screenshots, ...)
Many people are familiar with igraph in R, and want to use igraph-python in spyder, so I write a little widget named "network from tables" and a function graph2tables() to accomplish the task.
You may check out the details at https://github.com/icejean/orange3-glueviz.
Hope that it could do some help.

**Comment by ajdapretnar** [comment]
Thanks! As Glueviz is already an Orange add-on, where this widget is available, I am closing this.
