### ISSUE TITLE
[BUG] Computing Node-level indices when Network is constructed from columns

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-network#17]
Orange version: 3.3.9. 
Orange Network: last commit 9f152727f424fec65a1838b5460122d88bd614d4 

Fails when computing Node-level indices for columns. 

1. Construct a Network from distances where distances are computed between **columns**
2. Run Network analysis, and select e.g. Node-level indices > Degree

**Comment by kernc** [comment]
I guess the problem is in _Distances_ widget (or `DistMatrix`) which doesn't set `row_items` and `col_items` to transposed table. AFAIC, deferred till after pandas.

**Comment by janezd** [comment]
Fixed by #101.
