### ISSUE TITLE
Self-loops look strange in Network Explorer

### ISSUE THREAD

**Issue by thocevar** [biolab/orange3-network#188]
![image](https://user-images.githubusercontent.com/919223/106505397-8acf2480-64c8-11eb-9775-8fa677629085.png)

The selected node has a self-loop (it's not two nodes in the same place or something like that). This is from example dataset `mips_c2_cp_leu`.

**Comment by ajdapretnar** [comment]
I think this will be fixed in #178.

**Comment by thocevar** [comment]
No, not yet. :)

**Comment by janezd** [comment]
> No, not yet. :)

Should now.

**Comment by janezd** [comment]
Duplicate of #174.
