### ISSUE TITLE
Edge weights are not displayed in Network Explorer

### ISSUE THREAD

**Issue by thocevar** [biolab/orange3-network#189]
Consider the example network dataset `leu_by_genesets`. Ticking "Show edge weights" makes no difference. Visualization clearly uses some weights but won't show them.

![image](https://user-images.githubusercontent.com/919223/106506026-66c01300-64c9-11eb-91aa-4f7b6a0157be.png)

**Comment by janezd** [comment]
Works for me.

Have you selected any vertices? You have "Label only edges of selected nodes" checked.

**Comment by thocevar** [comment]
No, I haven't. Now that I do, it works as expected.
