### ISSUE TITLE
[BUG] Some SNAP Networks are not found.

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-network#20]
Orange version: 3.3.9.
Orange Network: last commit 9f15272

Automatically refresh SNAP Network list. Some, such as Facebook ego Network are not found (404 HTTP Error).

While at it, make sure the currently selected SNAP network remains highlighted when re-opening the widget.

**Comment by kernc** [comment]
Fixed in https://github.com/biolab/orange3-network/pull/14/commits/152a97a5ac803c48c29d8bf708f37540c1e4d7fd and https://github.com/biolab/orange3-network/pull/14/commits/b091c7f92e5002eefc54e7c6566dbd8d525e4ad4.
