### ISSUE TITLE
PyPI has version 1.5.1 and here the latest tag is 1.3.2: what is the latest version of orange3-network?

### ISSUE THREAD

**Issue by yurivict** [biolab/orange3-network#207]

**Comment by PrimozGodec** [comment]
The latest version is 1.5.1. Someone forgot to make a tag when releasing this add-on.

**Comment by yurivict** [comment]
So it would likely not get updated in the packaging systems because they get notified based on repository tags.

**Comment by PrimozGodec** [comment]
I can make a tag tommorow. :)

**Comment by PrimozGodec** [comment]
The tag for 1.5.1 is ready now.
