### ISSUE TITLE
Network Explorer: double zoom/commit button?

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#214]
##### Network version

1.6.0

##### Orange version

3.30.dev

##### Expected behavior
Network Explorer has a single Zoom/Commit option.

##### Actual behavior
There's a double box at the bottom, likely because ScatterplotGraph comes with its own one.

##### Steps to reproduce the behavior
Use Network Explorer with any dataset.

##### Additional info (worksheets, data, screenshots, ...)
![Uploading Screen Shot 2021-07-02 at 10.10.35.png…]()

**Comment by janezd** [comment]
I suppose merging #206 now fixed it? It doesn't happen to me.

**Comment by ajdapretnar** [comment]
Ah, ok. So #215 is irrelevant now?

**Comment by ajdapretnar** [comment]
Checked, it is fixed. I will remove this from #215, which now only has fixes related to sizing of the windows.

**Comment by janezd** [comment]
I'd merge it as it is (the change in Network Explorer is the same as in #206), but i'd like to resolve the failing tests first. @PrimozGodec has done this in #213, but I think we need to unpin more. Or there's something else we missed.

**Comment by janezd** [comment]
Two tests fail. One is related to summaries because Network Explorer has an ugly override of a signal name. I'll try to fix that.

The other is about embeddings, apparently some arguments of gensim. Do you know anything about this?

```
======================================================================
ERROR: test_call (tests.test_embeddings.TestEmbeddings)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\orange3-network\orange3-network\.tox\py-orange-latest\Lib\site-packages\orangecontrib\network\tests\test_embeddings.py", line 57, in test_call
    embeddings = n2v(self.toy_directed)
  File "D:\a\orange3-network\orange3-network\.tox\py-orange-latest\Lib\site-packages\orangecontrib\network\network\embeddings.py", line 134, in __call__
    model = Word2Vec(walks, size=self.emb_size, window=self.window_size, min_count=0, sg=1, workers=4,
TypeError: __init__() got an unexpected keyword argument 'size'
```

**Comment by ajdapretnar** [comment]
I'll check gensim.
