### ISSUE TITLE
Network Clustering: don't write to original data

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#226]
##### Network version

1.6.0

##### Orange version

3.30.dev

##### Expected behavior
Once Network Clustering is removed, there are no information on clusters in the data.

##### Actual behavior
Network Clustering writes to the original items file, which basically "backpropagates".

##### Steps to reproduce the behavior
Network File - Network Clustering - Network Explorer. There is "Cluster" variable present.
Network File - Network Explorer. There is also "Cluster" variable present, even though there should be none.

**Comment by janezd** [comment]
To whomever: `Network` should have a (shallow) `copy` method.

Then, of course, call it before adding cluster labels. Being shallow, the network will keep the same edges, but the table with data will (have to) be replaced because tables are immutable.
