### ISSUE TITLE
[BUG] OWNetworkExplorer: Change highlight when input changes

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#23]
When highlighting nodes by subset ID, highlights don't change when the input changes.

Try lastfm.net and select a subset with Data Table. Highlight the nodes by ID. Now change the selecting in a Data Table. Highlight doesn't change as it should.

**Comment by kernc** [comment]
Fixed in https://github.com/biolab/orange3-network/pull/14
