### ISSUE TITLE
Network file crashing when loading

### ISSUE THREAD

**Issue by petguy** [biolab/orange3-network#266]
##### Network version

**1.8.0**

##### Orange version

**3.36.1**

##### Expected behavior
Build several flows on the canvas using included network data. Replace the data with another file that I want to apply the same workflows and review. Network file widget: click folder to choose .TAB file, file loads

##### Actual behavior
Orange crashed initially. Trying to repeat this lead to the error below, but no crashes:
![image](https://github.com/biolab/orange3-network/assets/14867551/752d607f-559c-418e-a632-fb0d5ff87465)

##### Steps to reproduce the behavior
Build a flow using Network widgets and existing datasets. The double click Network file to choose another network file. Not sure if this is related, but Orange finds a .tab, .tsv, or .csv file with the same name as the .net file and imports it. The .net and .csv files are exported from gephi, which could mean a file interpretation problem.

##### Additional info (worksheets, data, screenshots, ...)
![image](https://github.com/biolab/orange3-network/assets/14867551/06d1bcc6-f5ae-4640-812d-e19ae550ca4b)
![image](https://github.com/biolab/orange3-network/assets/14867551/f31272d4-859a-497c-9bbb-e2d3c49fb9e6)

**Comment by janezd** [comment]
Thanks for your report, in particular the printouts, which made it easy to spot the problem. (Note to self: don't allow min to compare the second element, a variable, of `vars_and_overs` in https://github.com/biolab/orange3-network/blob/master/orangecontrib/network/widgets/OWNxFile.py#L252).

The (pretty embarrassing) bug is in the heuristic that sets the initial value of "Match node labels to data column". Based on the code, I suppose it will appear when the data contains two text columns whose elements that match the same number of labels in the network. The simplest case would be when your data contains two text equal columns.

It should be trivial to fix, and I believe that we'll release a new version in something like two weeks. If you need an urgent workaround - could you avoid having multiple such text columns?
