### ISSUE TITLE
Network Explorer terribly slow

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#40]
NE terribly slow on a network of 44 nodes and 10 edges (from grimm-tales-selected.tab - BoW - Network Distances).

**Comment by kernc** [comment]
Likely has to do with the number of (BoW) features the data contains which are put into Labels / Tooltips QListViews.

**Comment by kernc** [comment]
Commenting out this block avoids a O(n²) loop via _gui.py_. https://github.com/biolab/orange3-network/blob/57a25f9fbc7d69aa1bb2208f802b2fb7245ac269/orangecontrib/network/widgets/OWNxExplorer.py#L446-L449

**Comment by ajdapretnar** [comment]
Yes, very possibly this is the issue. We should think about a better solution (how many features to show if any).
