### ISSUE TITLE
Error: Changed NetworkX API

### ISSUE THREAD

**Issue by darjusp** [biolab/orange3-network#43]
hi guys,

Network explorer, throws an error (messages attached), in whichever way i am trying to connect it (based on distance file, generated network, or network file). I 'm using Mac OSx and Orange is standalone application, not withing Anaconda. Tried on Orange 3.6 and 3.7 versions. Network library is 1.2.0
![screen shot 2017-10-30 at 13 47 15](https://user-images.githubusercontent.com/10597360/32169373-ddb941b2-bd78-11e7-8e2f-9d8579484497.png)
![screen shot 2017-10-30 at 13 31 50](https://user-images.githubusercontent.com/10597360/32169376-dfb5a424-bd78-11e7-9c6c-0f50f9e7a2ac.png)

**Comment by kernc** [comment]
Thanks for the report. It appears networkx in its latest release purged some API we use.

You can try downgrading networkx to the previous stable version:

```bash
/Applications/Orange3.app/Contents/MacOS/pip install -U networkx==1.11
```

Note to self: This is the migration guide: https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

**Comment by darjusp** [comment]
Hi,

thank you, downgrading worked very well.. Now it works

**Comment by kernc** [comment]
The issue is still open, the API had changed.
