### ISSUE TITLE
[Question] Is it possible to create network from adjacency matrix?

### ISSUE THREAD

**Issue by darjusp** [biolab/orange3-network#45]
Hi, maybe such feature already exists within the package and i just haven't find it yet.
For instance i have such table (adjacency matrix), and would like to visualise it into the network.
Such table is not hard to create with Cooccurrence widget in Textable package, which also allows to transform data to Orange table, but is there away to proceed further from this?

![screen shot 2017-10-30 at 15 38 39](https://user-images.githubusercontent.com/10597360/32215778-9dd75a76-be2b-11e7-861f-0ded0f6400dc.png)

**Comment by kernc** [comment]
I don't think it's currently possible. It's possible to make a Network From Distances, but for that you need an instance of `DistMatrix`, not `Table`. Unfortunately no simple means of transforming one into the other.

Otoh, you could use Python Script widget with the following code:
```py
import numpy as np
from Orange.misc import DistMatrix

data = np.asarray(in_data) # convert in_data to numpy array
names = data[:, 0].astype(str)  # store first column (__unit2__)
data = data[:, 1:]  # strip first column from numeric data (__unit2__)
data = data.astype(float)  # convert to float, ensures only numbers present
# Ensure data is square matrix of len(names) elements
assert data.shape[0] == len(names)
assert data.shape[1] == len(names)

out_object = DistMatrix(data, names, names)
```
![screenshot_2017-10-31_16-52-26](https://user-images.githubusercontent.com/684364/32233957-f0d60d28-be5b-11e7-818c-deeb2b011bb4.png)

**Comment by astaric** [comment]
If you save the distances to a file, you could use the [Distance File](https://docs.orange.biolab.si/3/visual-programming/widgets/unsupervised/distancefile.html) widget to load the distances.

**Comment by darjusp** [comment]
Kernc, thanks a lot, actually your solution does the trick, although i don't understand what exactly it outputs :) Oh, and although i see names are saved, but I don't see them in the network close to the nodes. Something Im missing, or its just there are no such feature?

![screen shot 2017-10-31 at 22 34 48](https://user-images.githubusercontent.com/10597360/32247717-e0af7ff8-be8b-11e7-85a5-1656e54f5c39.png)

Astaric, cheers for the reply, but i am not sure i understand how to save 'data table' to .dst file, and actually not sure the file content will be the needed one.

**Comment by kernc** [comment]
Right. Try the script like so:
```py
import numpy as np
from Orange.misc import DistMatrix

data = np.asarray(in_data) # convert in_data to numpy array
data = data[:, 1:]  # strip first column from numeric data (__unit2__)
data = data.astype(float)  # convert to float, ensures only numbers present

out_object = DistMatrix(data, in_data)
```

**Comment by darjusp** [comment]
Excellent, thanks a lot again
