### ISSUE TITLE
Revise outdated documentation

### ISSUE THREAD

**Issue by xapple** [biolab/orange3-network#8]
I tired both on OS X and CentOS to do the following commands:

```
$ pip install orange-network
$ ipython -c "import Orange"
```

Same result both times:

```
/home/xapple/.local/lib/python2.7/site-packages/Orange/__init__.py:159: UserWarning: An exception occurred during the loading of 'network':
 AttributeError("'NoneType' object has no attribute 'replace'",)
   _import_addons()
```

**Comment by kernc** [comment]
The package name for Orange 3 add-on is orange3-network. Orange-network is the old, Orange2-only and apparently  less maintained version. If that's indeed what you're after, the old add-on's repository is [on BitBucket](https://bitbucket.org/biolab/orange-network/) where there is also already a [pull request that should fix](https://bitbucket.org/biolab/orange-network/pull-requests/2/ensure-__doc__-is-str-before-replacing/diff) the issue you report.

CC: @astaric

**Comment by xapple** [comment]
No I wasn't looking for old stuff. The newer the better is usually what I say.

It seems like you have a deeper problem then with distinguishing your versions. It's all mixed up:

I went here: https://github.com/biolab/orange3-network
The read me there is only three lines long, with the third line being a link to the documentation.
If you go to that documentation then the very first command you see is:

    pip install orange-network

**Comment by xapple** [comment]
In any case your error message should be more informative and calling a method on `None` reveals a problem in your programming logic.

**Comment by kernc** [comment]
That's a legitimate issue: the old, outdated documentation doesn't apply. Thanks!

**Comment by astaric** [comment]
I have merged the above mentioned pull request on bitbucket and contacted the PyPi maintainer as he needs to push a new release to pypi.

**Comment by xapple** [comment]
Hey that's great thanks, maybe I will use `Orange` in my latest data-mining/bioinfo tool development  after all.

**Comment by astaric** [comment]
Orange-network 0.3.5 has been released and published on PyPi.

**Comment by xapple** [comment]
Great, nice going ! Fast and responsive ! I'll try it out and let you know if I find other issues.

**Comment by ajdapretnar** [comment]
I'll update the readme. Thanks for reporting this!

**Comment by ajdapretnar** [comment]
I consider this issue fixed.
