### ISSUE TITLE
[ENH] Save Network

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-network#80]
##### Idea
Implement support for saving network files. As far as I understand, networks are currently NetworkX objects that cannot be stored simply. How could we go about this? I think this should be implemented in Save Data in core Orange.

**Comment by ajdapretnar** [comment]
@janezd @thocevar

**Comment by lanzagar** [comment]
Save Data is a widget that saves Table objects to files. We have a separate widget Save Model for example.
I think networks should probably have their own widget for saving and I don't see a reason to have it in core Orange if network functionalities are only available through a special addon (saving should also be part of that addon then)?

**Comment by ajdapretnar** [comment]
Ok. I agree.
Another thing to discuss is what to save and how. Could @thocevar elaborate on this a bit more, please? As far as I understand, the procedure is not totally straightforward.

**Comment by thocevar** [comment]
The Graph structure is an extension of the NetworkX's Graph that also contains the node descriptions as a Table (items). Besides the items, we should also store the network structure in an easy to read/parse format - almost any from https://networkx.github.io/documentation/stable/reference/readwrite/index.html will do.

Anyway, I suggest we wait for the reconstruction of the add-on before proceeding.
