### ISSUE TITLE
How to visualize separate Nodes File and Edges File as CSV

### ISSUE THREAD

**Issue by ncdingari** [biolab/orange3-network#81]
I am trying to visualize a network by adding the nodes.csv and edges.csv into File and then connecting to Network explorer. Its not working. 
![image](https://user-images.githubusercontent.com/6037028/44055062-4071c59c-9f12-11e8-89a3-c2b95539416f.png)
It would be great if you could provide an example at http://orange3-network.readthedocs.io/

**Comment by kernc** [comment]
Networks can currently be loaded via [Network File](http://orange3-network.readthedocs.io/en/latest/widgets/networkfile.html) widget or constructed with [Network from Distances](http://orange3-network.readthedocs.io/en/latest/widgets/networkfromdistances.html) widget.

If you were expecting to pass in edges as `<U,V>` pairs, this is not currently supported or on the roadmap. Perhaps easiest that your file be adapted into a [Pajek file](https://gephi.org/users/supported-graph-formats/pajek-net-format/) that Orange can read.

**Comment by ncdingari** [comment]
I created a "Pajek" format Network file and tried to load. It gave the following error


`

Exception: | ValueError: not enough values to unpack (expected 2, got 1)
-- | --
Module: | networkx.readwrite.pajek:192
Widget Name: | Network File
Widget Module: | orangecontrib.network.widgets.OWNxFile:254
Widget Scheme: | C:\Users\dingarin\AppData\Local\Temp\ows-2n56lsc6.ows.xml
Version: | 3.15.0
Environment: | Python 3.6.4 on Windows 10 10.0.14393 AMD64
Installed Packages: | AnyPyTools==0.13.0, AnyQt==0.0.8, Automat==0.7.0, Babel==2.5.3, Bottleneck==1.2.1, CacheControl==0.12.5, CommonMark==0.7.5, Cython==0.28.4, Flask-Cors==3.0.3, Flask==0.12.2, Jinja2==2.10, Keras==2.1.5, LTTL==2.0.6, Markdown==2.6.11, MarkupSafe==1.0, Orange-Spectroscopy==0.3.7, Orange3-Associate==1.1.5, Orange3-Educational==0.1.8, Orange3-Geo==0.2.3, Orange3-ImageAnalytics==0.2.1, Orange3-Network==1.3.2, Orange3-Prototypes==0.10.2, Orange3-Text==0.4.0, Orange3-Textable==3.0.7, Orange3-Timeseries==0.3.3, Orange3==3.15.0, Pillow==5.0.0, PyHive==0.5.1, PyJWT==1.6.4, PyOpenGL==3.1.1a1, PySocks==1.6.7, PyWavelets==0.5.2, PyYAML==3.12, Pygments==2.2.0, QtAwesome==0.4.4, QtPy==1.4.1, SQLAlchemy==1.2.7, Send2Trash==1.4.2, Shapely==1.6.4.post1, Sphinx==1.6.6, TPOT==0.9.3, Theano==1.0.2, Twisted==18.7.0, Werkzeug==0.14.1, XlsxWriter==0.9.8, absl-py==0.2.2, alabaster==0.7.10, anaconda-client==1.6.14, anaconda-navigator==1.8.7, anaconda-project==0.8.2, aplus==0.11.0, appdirs==1.4.3, asn1crypto==0.24.0, astor==0.6.2, astroid==1.6.1, astropy==2.0.3, attrs==17.4.0, backports.functools-lru-cache==1.5, backports.shutil-get-terminal-size==1.0.0, beakerx==1.0.0, beautifulsoup4==4.6.0, biopython==1.72, bitarray==0.8.1, bkcharts==0.2, blaze==0.11.3, bleach==1.5.0, bokeh==0.12.13, boto3==1.7.24, boto==2.48.0, botocore==1.10.24, bqplot==0.11.0, brotlipy==0.7.0, bz2file==0.98, cachetools==2.1.0, cairocffi==0.8.0, certifi==2018.8.13, cffi==1.11.5, chardet==3.0.4, click==6.7, cloudpickle==0.5.2, clyent==1.2.2, colorama==0.3.9, colorcet==0.9.1, comtypes==1.1.4, conda-build==3.4.1, conda-verify==2.0.0, conda==4.5.10, constantly==15.1.0, contextlib2==0.5.5, cryptography==2.1.4, cycler==0.10.0, cymem==1.31.2, cytoolz==0.8.2, dask==0.16.1, datashape==0.5.4, deap==1.2.2, decorator==4.2.1, dill==0.2.7.1, distributed==1.20.2, docrep==0.2.3, docutils==0.14, docx2txt==0.7, en-core-web-sm==2.0.0, entrypoints==0.2.3, et-xmlfile==1.0.1, fast-histogram==0.3, fastcache==1.0.2, fasteners==0.14.1, filelock==2.0.13, funcargparse==0.2.0, future==0.16.0, gast==0.2.0, gensim==3.4.0, geojson==2.3.0, gevent==1.2.2, glob2==0.6, glue-core==0.13.3, glue-vispy-viewers==0.10, gmaps==0.8.0, greenlet==0.4.12, grpcio==1.12.0, h2==2.6.2, h5py==2.7.1, heapdict==1.0.0, hpack==3.0.0, html5lib==0.9999999, hyperframe==3.2.0, hyperlink==18.0.0, hypertemp==0.8.0, idna==2.6, imageio==2.2.0, imagesize==0.7.1, impyla==0.14.1, incremental==17.5.0, ipykernel==4.8.2, ipyleaflet==0.9.0, ipympl==0.2.1, ipython-genutils==0.2.0, ipython==6.2.1, ipyvolume==0.4.6, ipywebrtc==0.3.0, ipywidgets==7.3.1, isort==4.2.15, itsdangerous==0.24, jdcal==1.3, jedi==0.11.1, jmespath==0.9.3, joblib==0.11, jsonschema==2.6.0, jupyter-client==5.2.2, jupyter-console==5.2.0, jupyter-core==4.4.0, jupyter==1.0.0, jupyterlab-launcher==0.11.2, jupyterlab==0.33.11, keyring==12.0.1, keyrings.alt==3.0, lazy-object-proxy==1.3.1, llvmlite==0.21.0, locket==0.2.0, lockfile==0.12.2, lxml==4.1.1, mako==1.0.7, matplotlib==2.1.2, mccabe==0.6.1, menuinst==1.4.11, mistune==0.8.3, monotonic==1.5, more-itertools==4.1.0, mpl-scatter-density==0.3, mpmath==1.0.0, msgpack-numpy==0.4.3.1, msgpack-python==0.5.1, msgpack==0.5.6, multipledispatch==0.4.9, murmurhash==0.28.0, navigator-updater==0.1.0, nbconvert==5.3.1, nbformat==4.4.0, networkx==2.1, nltk==3.2.5, nose==1.3.7, notebook==5.6.0, numba==0.36.2, numexpr==2.6.4, numpy==1.13.3, numpydoc==0.7.0, oauthlib==2.1.0, odfpy==1.3.6, odo==0.5.1, olefile==0.45.1, openpyxl==2.4.10, opusFC==1.1.1, packaging==16.8, pandas-datareader==0.6.0, pandas==0.22.0, pandocfilters==1.4.2, parso==0.1.1, partd==0.3.8, path.py==10.5, pathlib2==2.3.0, pathlib==1.0.1, patsy==0.5.0, pdfminer3k==1.3.1, pep8==1.7.1, pickleshare==0.7.4, pip==18.0, pkginfo==1.4.1, plac==0.9.6, plotly==3.1.1, pluggy==0.6.0, ply==3.10, pockets==0.6.2, preshed==1.0.0, progressbar2==3.38.0, prometheus-client==0.3.1, prompt-toolkit==1.0.15, protobuf==3.5.2, psutil==5.4.3, psyplot-gui==1.1.0, psyplot==1.1.0.post1, pure-sasl==0.5.0, py4j==0.10.7, py==1.5.2, pyDOE==0.3.8, pyOpenSSL==17.5.0, pyasn1-modules==0.2.2, pyasn1==0.4.4, pycairo==1.13.3, pycodestyle==2.3.1, pycosat==0.6.3, pycparser==2.18, pycrypto==2.6.1, pycurl==7.43.0.1, pyflakes==1.6.0, pygments-anyscript==1.1.0, pygpu==0.7.6, pylint==1.8.2, pyntacle==0.1.3, pyodbc==4.0.22, pyparsing==2.2.0, pyqtgraph==0.10.0, pyreadline==2.1, pytest-runner==4.2, pytest==3.5.1, python-dateutil==2.6.1, python-igraph==0.7.1.post6, python-louvain==0.11, python-utils==2.3.0, pythreejs==0.4.1, pytz==2017.3, pywin32==222, pywinpty==0.5, pyzmq==17.0.0, qtconsole==4.3.1, qutip==4.2.0, regex==2017.11.9, requests-file==1.4.3, requests-ftp==0.3.1, requests-oauthlib==1.0.0, requests==2.18.4, retrying==1.3.3, rfc3986==1.1.0, rope==0.10.7, ruamel-yaml==0.15.35, s3transfer==0.1.13, scikit-image==0.13.1, scikit-learn==0.19.1, scipy==1.0.0, seaborn==0.8.1, serverfiles==0.2.1, service-identity==17.0.0, setuptools-git==1.2, setuptools==38.4.0, simhash==1.9.0, simplegeneric==0.8.1, simplejson==3.16.0, singledispatch==3.4.0.3, six==1.11.0, smart-open==1.5.7, snowballstemmer==1.2.1, sortedcollections==0.5.3, sortedcontainers==1.5.9, spacy==2.0.11, spectral==0.19, sphinx-rtd-theme==0.4.1, sphinxcontrib-napoleon==0.6.1, sphinxcontrib-websupport==1.0.1, spyder-kernels==0.2.4, spyder==3.3.1, statsmodels==0.8.0, stencila==0.28.1, stopit==1.1.2, swaggerpy==0.2.1, sympy==1.1.1, tables==3.4.2, tblib==1.3.2, tensorboard==1.8.0, tensorflow==1.8.0, termcolor==1.1.0, terminado==0.8.1, testpath==0.3.1, thinc==6.10.1, thrift-sasl==0.3.0, thrift==0.11.0, thriftpy==0.3.9, toolz==0.9.0, tornado==4.5.3, tqdm==4.23.4, traitlets==4.3.2, traittypes==0.2.1, tweepy==3.6.0, typing==3.6.2, ujson==1.35, unicodecsv==0.14.1, update-checker==0.16, urllib3==1.22, vaex-astro==0.2.0, vaex-core==0.4.0, vaex-distributed==0.2.0, vaex-hdf5==0.2.1, vaex-jupyter==0.2.1, vaex-server==0.2.1, vaex-ui==0.2.0, vaex-viz==0.3.0, validate-email==1.3, wcwidth==0.1.7, webencodings==0.5.1, websocket-client==0.48.0, wheel==0.30.0, widgetsnbextension==3.3.1, wikipedia==1.4.0, win-inet-pton==1.0.1, win-unicode-console==0.5, wincertstore==0.2, wrapt==1.10.11, xarray==0.10.8, xgboost==0.72, xlrd==1.1.0, xlwings==0.11.5, xlwt==1.3.0, zict==0.1.3, zope.interface==4.5.0
Machine ID: | 176830161863752
Stack Trace: | Traceback (most recent call last):  File "C:\ProgramData\Anaconda3\lib\site-packages\orangecontrib\network\widgets\OWNxFile.py", line 254, in browseNetFile    self.selectNetFile()  File "C:\ProgramData\Anaconda3\lib\site-packages\orangecontrib\network\widgets\OWNxFile.py", line 117, in selectNetFile    self.openNetFile(self.recentFiles[0])  File "C:\ProgramData\Anaconda3\lib\site-packages\orangecontrib\network\widgets\OWNxFile.py", line 140, in openNetFile    G = network.readwrite.read(filename, auto_table=self.auto_table)  File "C:\ProgramData\Anaconda3\lib\site-packages\orangecontrib\network\readwrite.py", line 134, in read    return read_pajek(path, encoding, auto_table=auto_table)  File "C:\ProgramData\Anaconda3\lib\site-packages\orangecontrib\network\readwrite.py", line 253, in read_pajek    G = _wrap(rwpajek.read_pajek(path))  File "<decorator-gen-408>", line 2, in read_pajek  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\utils\decorators.py", line 227, in _open_file    result = func_to_be_decorated(*new_args, **kwargs)  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\readwrite\pajek.py", line 142, in read_pajek    return parse_pajek(lines)  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\readwrite\pajek.py", line 192, in parse_pajek    id, label = splitline[0:2]ValueError: not enough values to unpack (expected 2, got 1)
Local Variables: | OrderedDict([('G',              <networkx.classes.multidigraph.MultiDiGraph object at 0x00000244D0EE32B0>),             ('i', 0),             ('l', '*Arcs\r'),             ('labels', []),             ('lines', <list_iterator object at 0x00000244D0EE3390>),             ('nnodes', '5'),             ('nodelabels', {}),             ('shlex',              <module 'shlex' from 'C:\\ProgramData\\Anaconda3\\lib\\shlex.py'>),             ('splitline', ['*Arcs'])])

`

**Comment by kernc** [comment]
If NetworkX, the library Orange uses to read and represent graphs, cannot read your file, as it appears, the file might be invalid. What's your file like?

**Comment by ncdingari** [comment]
I have created the "Pajek" file in R using "igraph" using

`write_graph(graphExample, file='graphExample.net', format = "pajek")`

**Comment by kernc** [comment]
If you think this is an issue of reading a valid pajek file, please [raise the issue on NetworkX](https://github.com/networkx/networkx).

**Comment by icejean** [comment]
Hi, I write a widget to create a network from vertices&edges orange data tables,
you may check it out at https://github.com/icejean/orange3-glueviz.
