### ISSUE TITLE
Network File crashed when I pull it into canvas

### ISSUE THREAD

**Issue by JackYangzg** [biolab/orange3-network#88]
Stack Trace: | Traceback (most recent call last):  File "D:\ProgramData\Anaconda3\envs\orange\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 580, in create_widget_instance    widget.__init__()  File "D:\ProgramData\Anaconda3\envs\orange\lib\site-packages\orangecontrib\network\widgets\OWNxFile.py", line 85, in __init__    self.reload()  File "D:\ProgramData\Anaconda3\envs\orange\lib\site-packages\orangecontrib\network\widgets\OWNxFile.py", line 89, in reload    self.selectNetFile()  File "D:\ProgramData\Anaconda3\envs\orange\lib\site-packages\orangecontrib\network\widgets\OWNxFile.py", line 117, in selectNetFile    self.openNetFile(self.recentFiles[0])  File "D:\ProgramData\Anaconda3\envs\orange\lib\site-packages\orangecontrib\network\widgets\OWNxFile.py", line 140, in openNetFile    G = network.readwrite.read(filename, auto_table=self.auto_table)  File "D:\ProgramData\Anaconda3\envs\orange\lib\site-packages\orangecontrib\network\readwrite.py", line 137, in read    return read_edgelist(path, auto_table)  File "D:\ProgramData\Anaconda3\envs\orange\lib\site-packages\orangecontrib\network\readwrite.py", line 185, in read_edgelist    G.set_items(graph_to_table(G))  File "D:\ProgramData\Anaconda3\envs\orange\lib\site-packages\orangecontrib\network\readwrite.py", line 114, in graph_to_table    return tableUnboundLocalError: local variable 'table' referenced before assignment
-- | --

**Comment by janezd** [comment]
I can't replicate this - I can't create a file that results in an empty graph. But I fixed the problem. I hope.
