### ISSUE TITLE
setup.py should fail if Python < 3.4

### ISSUE THREAD

**Issue by xapple** [biolab/orange3-network#9]
I tired both on OS X and CentOS to do the following commands:

```
$ pip install orange3-network
$ ipython -c "import Orange"
```

Same result both times:

```
/home/xapple/.local/lib/python2.7/site-packages/Orange/__init__.py:159: UserWarning: Importing add-on 'network' failed: cannot import name DiscreteVariable
  _import_addons()
```

**Comment by xapple** [comment]
I thought it might be due to a mismatch with the other Orange module, but it does't seem so:

    xapple@ww-hmem02 ~ $ pip install Orange3
    Collecting Orange3
      Could not find a version that satisfies the requirement Orange3 (from versions: )
    No matching distribution found for Orange3
    xapple@ww-hmem02 ~ $ pip install Orange2
    Collecting Orange2
      Could not find a version that satisfies the requirement Orange2 (from versions: )
    No matching distribution found for Orange2
    xapple@ww-hmem02 ~ $ pip install Orange
    Requirement already satisfied (use --upgrade to upgrade): Orange in ./.local/lib/python2.7/site-packages

**Comment by kernc** [comment]
Yes, Orange3 is not (yet) on pip. You have to install it through [binary distributable](http://orange.biolab.si/) or through [source](https://github.com/biolab/orange3). Note, Orange3 (and Orange3-network) are Python 3+ only.

**Comment by xapple** [comment]
Well that's fine if it's not ready, but any user checking out your product at the moment is just going to find it in a non-working state, with contradictory documentation. If I were you I would not advertise until it is ready, or add visible warnings.

**Comment by kernc** [comment]
Well, if you install Orange 3 first, and then install Orange3-network in the same Python 3 environment either via command line or through the menu (Options > Add-ons ...), it should install and work as advertised. The documentation is indeed stale, sorry.

**Comment by xapple** [comment]
OK well I understand better. I might try it. But I have never yet made the jump to 3. It's quite risky to do that, especially in the scientific community where almost everyone is still at 2.7.x

In any case your error message should be more informative and should say that there is a mismatch between versions when this happens.
